version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gensim
    versions:
    - ">= 4.a, < 5"
  - dependency-name: h5py
    versions:
    - ">= 3.a, < 4"
  - dependency-name: keras
    versions:
    - "> 2.2.4"
  - dependency-name: keras-bert
    versions:
    - ">= 0.86.a, < 0.87"
  - dependency-name: lmdb
    versions:
    - ">= 1.a, < 2"
  - dependency-name: numpy
    versions:
    - "> 1.16.1, < 2"
  - dependency-name: numpy
    versions:
    - ">= 1.17.a, < 1.18"
  - dependency-name: scikit-learn
    versions:
    - ">= 0.24.a, < 0.25"
  - dependency-name: tensorflow
    versions:
    - ">= 2.a, < 3"
  - dependency-name: delft
    versions:
    - 0.2.5
    - 0.2.6
  - dependency-name: papermill
    versions:
    - 2.3.1
  - dependency-name: pandas
    versions:
    - 1.2.1
