version: '3'

services:
  # the main delft image that we are going to push
  delft:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        install_dev: y
    image: elifesciences/sciencebeam-trainer-delft:${IMAGE_TAG}
    volumes:
      - data:/opt/sciencebeam-trainer-delft/data

  # grobid with delft
  grobid:
    build:
      context: .
      dockerfile: Dockerfile.grobid
      args:
        base_image: ${BASE_GROBID_REPO}:${BASE_GROBID_TAG}
    image: elifesciences/sciencebeam-trainer-delft-grobid:${BASE_GROBID_TAG}-${IMAGE_TAG}
    environment:
      - OVERRIDE_MODELS=${OVERRIDE_MODELS}
      - DISABLE_LMDB_CACHE=${DISABLE_LMDB_CACHE}
      - EMBEDDING_LMDB_PATH=${EMBEDDING_LMDB_PATH}
      - PRELOAD_EMBEDDING=${PRELOAD_EMBEDDING}
    volumes:
      - data:/opt/sciencebeam-trainer-delft/data
    ports:
      - "${GROBID_PORT}:8070"

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    image: elifesciences/sciencebeam-trainer-delft-jupyter:${IMAGE_TAG}
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "${SCIENCEBEAM_JUPYTER_PORT}:8888"

volumes:
  data:
