version: '3'

services:
  # the main delft image that we are going to push
  delft:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        delft_repo: ${DELFT_REPO}
        delft_tag: ${DELFT_TAG}
        install_dev: y
    image: elifesciences/sciencebeam-trainer-delft:${IMAGE_TAG}
    volumes:
      - data:/data

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    image: elifesciences/sciencebeam-trainer-delft-jupyter:${IMAGE_TAG}
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "${SCIENCEBEAM_JUPYTER_PORT}:8888"

volumes:
  data:
