version: '3'

services:
  delft:
    volumes:
      - ./sciencebeam_trainer_delft:/opt/sciencebeam-trainer-delft/sciencebeam_trainer_delft
      - ./tests:/opt/sciencebeam-trainer-delft/tests
      - ~/.config/gcloud:/root/.config/gcloud

  grobid:
    volumes:
      - ./sciencebeam_trainer_delft:/opt/sciencebeam-trainer-delft/sciencebeam_trainer_delft
      - ${LOCAL_DATA_DIR}:/data
      - ./embedding-registry.json:/opt/sciencebeam-trainer-delft/embedding-registry.json

  jupyter:
    environment:
      - NB_UID=${NB_UID}
      - NB_GID=${NB_GID}
    volumes:
      - .:/home/jovyan/sciencebeam-trainer-delft
      - ~/.config/gcloud:/home/jovyan/.config/gcloud
