version: '3'

services:
  delft:
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud

  jupyter:
    environment:
      - NB_UID=${NB_UID}
      - NB_GID=${NB_GID}
    volumes:
      - .:/home/jovyan/sciencebeam-trainer-delft
      - ~/.config/gcloud:/home/jovyan/.config/gcloud
