grobid:
  # NOTE: change these values to absolute paths when running on production
  grobidHome: "grobid-home"
  
  # how to load the models, 
  # false -> models are loaded when needed (default), avoiding putting in memory useless models
  # true -> all the models are loaded into memory at the server startup, slow the start of the services and models not
  # used will take some memory
  modelPreload: false

  # CORS configuration
  corsAllowedOrigins: "*"
  corsAllowedMethods: "OPTIONS,GET,PUT,POST,DELETE,HEAD"
  corsAllowedHeaders: "X-Requested-With,Content-Type,Accept,Origin"

server:
    type: custom
    applicationConnectors:
    - type: http
      port: 8070
    adminConnectors:
    - type: http
      port: 8071
    registerDefaultExceptionMappers: false


logging:
  level: DEBUG
  loggers:
    org.apache.pdfbox.pdmodel.font.PDSimpleFont: "OFF"
  appenders:
    - type: console
      threshold: INFO
      timeZone: UTC
    - type: file
      currentLogFilename: logs/grobid-service.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: logs/grobid-service-%d.log
      archivedFileCount: 5
      timeZone: UTC
